aplicaciones/departamento/urls.py
from django.urls import path,include
from aplicaciones.departamento.views import DepartamentoListView, FiltrarEmpleados
app_name = 'departamento_app'
urlpatterns = [
    path('',DepartamentoListView.as_view()),
    path('filtrar_empleados/<nombre_corto>/',FiltrarEmpleados.as_view(), name = "filtro")
]

aplicaciones/empleados/urls.py
from django.urls import path,include
from aplicaciones.empleados.views import EmpleadosListView,EmpleadoDetallado,AdministrarEmpleado,EditarEmpleado,EliminarEmpleado,CrearEmpleado
app_name = 'empleado_app'
urlpatterns = [
    path('',EmpleadosListView.as_view(), name = "generico"),
    path('detallado/<pk>/',EmpleadoDetallado.as_view(), name = "Detallado"),
    path('administrar/',AdministrarEmpleado.as_view(), name = "administrar"),
    path('editar/<pk>/',EditarEmpleado.as_view(), name = "editar"),
    path('eliminar/<pk>/',EliminarEmpleado.as_view(),name = "eliminar"),
    path('registrar/',CrearEmpleado.as_view(),name = "registrar")
]

aplicaciones/home/urls.py
from django.urls import path,include
from .views import vistaInicial
urlpatterns = [
    path('',vistaInicial.as_view()),
    path('empleados/',include('aplicaciones.empleados.urls')),
    path('departamento/',include('aplicaciones.departamento.urls'))
]

proyecto/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('aplicaciones.home.urls'))
]

aplicaciones/departamento/models.py
from django.db import models
class Departamento (models.Model):
    nombre_departamento = models.CharField(("Nombre"), max_length=50, blank = True)
    nombre_corto_departamento = models.CharField(("Psudonimo"), max_length=20)
    activo_departamento = models.BooleanField(("False"),default = False)
    def __str__(self):
        return str(self.id)+"-"+self.nombre_departamento
# Create your models here.

aplicaciones/empleados/models.py
from django.db import models
from aplicaciones.departamento.models import Departamento

class Habilidades(models.Model):
    habilidad = models.CharField(("Habilidad"), max_length=50)
    def __str__(self):
        return str(self.id)+"-"+self.habilidad
class Empleado (models.Model):
    opciones_trabajo = (('0','Contador'),('1','Cantante'),('2','Ecologa'),('3','Futbolista'))
    nombre_empleado = models.CharField(("Nombres"), max_length=60)
    apellido_empleado = models.CharField(("Apellidos"), max_length=60)
    trabajo_empleado = models.CharField(("Empleo"), max_length=100, choices = opciones_trabajo)
    departamento = models.ForeignKey((Departamento), on_delete = models.CASCADE)
    habilidad = models.ManyToManyField((Habilidades))
    nombre_completo_mpleado = models.CharField(("Nombre Completo"), max_length=120, blank = True)
    def __str__(self):
        return str(self.id)+"-"+self.nombre_empleado
# Create your models here.

aplicaciones/home/models.py
from django.db import models

# Create your models here.

aplicaciones/departamento/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Departamento
from aplicaciones.empleados.models import Empleado
class DepartamentoListView(ListView):
    model = Departamento
    template_name = "departamento/listar_departamentos.html"
    context_object_name = "departamento"

class FiltrarEmpleados(ListView):
    model = Empleado
    template_name = "empleados/empleados.html"
    context_object_name = "empleado"
    def get_queryset(self):
        nombre_corto_1 = self.kwargs['nombre_corto']
        lista = Empleado.objects.filter(departamento__nombre_corto_departamento=nombre_corto_1)
        return lista

aplicaciones/empleados/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views.generic import ListView,DetailView,DeleteView,UpdateView,CreateView
from .models import Empleado
from django.urls import reverse_lazy
class EmpleadosListView(ListView):
    model = Empleado
    template_name = "empleados/empleados.html"
    paginate_by = 6
    context_object_name = "empleado"
    def get_queryset(self):
        palabra_clave = self.request.GET.get("nombre",'')
        lista = Empleado.objects.filter(nombre_empleado__icontains = palabra_clave)
        if len(lista)>0:
            return lista
        else:
            return super().get_queryset()
        
class EmpleadoDetallado(DetailView):
    model = Empleado
    template_name = "empleados/empleado_detallado.html"
    context_object_name = "empleado"
    
class AdministrarEmpleado(ListView):
    model = Empleado
    template_name = "empleados/administrar.html"
    paginate_by = 6
    context_object_name = "empleado"

class EditarEmpleado(UpdateView):
    model = Empleado
    template_name = "empleados/editar.html"
    fields = ('__all__')
    success_url = reverse_lazy('empleado_app:generico')
    context_object_name = "empleado"

class EliminarEmpleado(DeleteView):
    model = Empleado
    template_name = "empleados/eliminar.html"
    success_url = reverse_lazy('empleado_app:administrar')
    context_object_name = "empleado"
    def get_queryset(self):
        palabra_clave = self.request.GET.get("nombre",'')
        lista = Empleado.objects.filter(nombre_empleado__icontains = palabra_clave)
        if len(lista)>0:
            return lista
        else:
            return super().get_queryset()

class CrearEmpleado(CreateView):
    model = Empleado
    template_name = "empleados/crear.html"
    success_url = reverse_lazy('empleado_app:generico')
    fields = ('__all__')
# Create your views here.

aplicaciones/home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

class vistaInicial(TemplateView):
    template_name = "home/inicio.html"
# Create your views here.

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titulo %}{% endblock titulo %}</title>
    <link href = "{%static 'css/general/nav_bar.css'%}" rel = "stylesheet"/>
    {%block configuraciones%}{%endblock configuraciones%}
</head>
<body>
    <div class = "nav">
        {%block administrar%}{%endblock administrar%}
        <div>
            <a href = "/empleados">Empleados</a><br/>
        </div>
        <div>
            <a href = "/departamento">Departamentos</a><br/>
        </div>
        <div>
            <a href = "/">Inicio</a> <br/>
        </div>
    </div>
    {%block contenido%}{%endblock contenido%}
</body>
</html>

templates/departamento/listar_departamentos.html
{%extends 'base.html'%}
{%load static%}
{%block configuraciones%}
<link href = "{%static 'css/empleados/tabla.css'%}" rel = "stylesheet"/>
{%endblock configuraciones%}
{%block contenido%}
<div class = "contenedor_global">
    <div>
        <table>
            <tr>
                <th>
                    DEPARTAMENTO
                </th>
                <th>
                    PSEUDONIMO
                </th>
                <th>
                    EMPLEADOS
                </th>
            </tr>
            {% for i in departamento%}
            <tr>
                <td>
                    {{i.nombre_departamento}}
                </td>
                <td>
                    {{i.nombre_corto_departamento}}
                </td>
                <td>
                    <a href = "{%url 'departamento_app:filtro' i.nombre_corto_departamento%}">VER</a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
{%endblock contenido%}

templates/empleados/administrar.html
{%extends 'base.html'%}
{%load static%}
{%block configuraciones%}
<link href = "{%static 'css/empleados/tabla.css'%}" rel = "stylesheet"/>
{%endblock configuraciones%}
{%block administrar%}
<div>
    <a href = "{%url 'empleado_app:administrar'%}" style = "color:red">Administrar</a>
</div>
<div>
    <a href = "{%url 'empleado_app:registrar'%}" style = "color:red">Registrar</a>
</div>
{%endblock administrar%}
{%block contenido%}
<br/>
<div class = "busqueda">
    <form method = "GET">
        <input type = "text" class = "caja_busqueda" placeholder = "Nombre empleado" id = "nombre" name = "nombre">
        <input type = "submit"/ value = "🔍︎" class = "boton_buscar">
    </form>
</div>
<div class = "contenedor_global">
    <div>
        <table>
            <tr>
                <th>
                    NOMBRES
                </th>
                <th>
                    APELLIDOS
                </th>
                <th>
                    DEPARTAMENTO
                </th>
                <th>
                    ACCION
                </th>
            </tr>
            {% for i in empleado %}
            <tr>
                <td>
                    {{i.nombre_empleado}}
                </td>
                <td>
                    {{i.apellido_empleado}}
                </td>
                <td>
                    {{i.departamento.nombre_departamento}}
                </td>
                <td>
                    <a href = "{%url 'empleado_app:editar' i.id%}">EDITAR </a> |
                    <a href = "{%url 'empleado_app:eliminar' i.id%}">ELIMINAR</a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
    <div class = "pagina">
        {%if is_paginated%}
        <ul>
            {% if page_obj.has_previous%}
            <li>
                <a href = "?page={{page_obj.previous_page_number}}"><<</a>
            </li>
            {%endif%}
            {% for pagina in paginator.page_range%}
            {% if pagina == page_obj.number %}
            <li>
                <a href = "?page={{pagina}}" class = "pagina_actual">{{pagina}}</a>
            </li>
            {%else%}
            <li>
                <a href = "?page={{pagina}}">{{pagina}}</a>
            </li>
            {% endif%}
            {%endfor%}
            {% if page_obj.has_next%}
            <li>
                <a href = "?page={{page_obj.next_page_number}}">>></a>
            </li>
            {%endif%}
        </ul>
        {%endif%}
    </div>
    {%endblock contenido%}
</div>

templates/empleados/crear.html
{%extends 'base.html'%} {%load static%} {%block configuraciones%}
<link href="{%static 'css/empleados/editar.css'%}" rel="stylesheet" />
{%endblock configuraciones%} {%block contenido%}
<br />
<form method="POST">
  {%csrf_token%}
  <div class="contenedor_global">
    <div class="Contenedor">
      <span> <label>Nombre.</label>{{form.nombre_empleado}} </span>
      <span> <label>Apelli.</label>{{form.apellido_empleado}} </span>
      <span> <label>Trabaj.</label>{{form.trabajo_empleado}} </span>
      <span> <label>Depart.</label>{{form.departamento}} </span>
      <span> <label>Habili.</label>{{form.habilidad}} </span>
      <span> <label>Comple.</label>{{form.nombre_completo_mpleado}} </span>
      <input type="submit" value="Enviar" />
    </div>
  </div>
</form>
{%endblock contenido%}

templates/empleados/editar.html
{%extends 'base.html'%} {%load static%} {%block configuraciones%}
<link href="{%static 'css/empleados/editar.css'%}" rel="stylesheet" />
{%endblock configuraciones%} {%block contenido%}
<br />
<form method="POST">
  {%csrf_token%}
  <div class="contenedor_global">
    <div class="Contenedor">
      <span> <label>Nombre.</label>{{form.nombre_empleado}} </span>
      <span> <label>Apelli.</label>{{form.apellido_empleado}} </span>
      <span> <label>Trabaj.</label>{{form.trabajo_empleado}} </span>
      <span> <label>Depart.</label>{{form.departamento}} </span>
      <span> <label>Habili.</label>{{form.habilidad}} </span>
      <span> <label>Comple.</label>{{form.nombre_completo_mpleado}} </span>
      <input type="submit" value="Enviar" />
    </div>
  </div>
</form>
{%endblock contenido%}

templates/empleados/eliminar.html
{%extends 'base.html'%}
{%load static%}
{%block configuraciones%}
<link href = "{%static 'css/empleados/eliminar.css'%}" rel = "stylesheet"/>
{%endblock configuraciones%}
{%block contenido%}
<div class = "contenedor">
    <h1>¿Realmente desea eliminar al empleado <b>{{empleado.nombre_empleado}} {{empleado.apellido_empleado}}</b>?</h1>
    <form method = "post">{%csrf_token%}
        <input type = "submit" value = "SI"/>
    </form>
</div>
{%endblock contenido%}

templates/empleados/empleado_detallado.html
{%extends 'base.html'%} 
{%load static%}
{%block configuraciones%}
<link href = "{%static 'css/empleados/detallado.css'%}" rel = "stylesheet"/>
{%endblock configuraciones%}
{%block contenido%}
<div class="container">
  <div class="square">
    <div>
      <img
        src="{%static 'img/empleados/empleado_1.webp'%}"
        class="imagen_empleado"
      />
    </div>
    <div>
      <h2>{{empleado.nombre_completo_mpleado}}</h2>
    </div>
    <div>
        <p>
            Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de
            texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias
            desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la
            imprenta) desconocido usó una galería de textos y los mezcló de tal manera que
            logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino
            que tambien ingresó como texto de relleno en documentos electrónicos, quedando
            esencialmente igual al original. Fue popularizado en los 60s con la creación
            de las hojas "Letraset", las cuales contenian pasajes de Lorem Ipsum, y más
            recientemente con software de autoedición, como por ejemplo Aldus.
          </p>
    </div>
  </div>
</div>
{%endblock contenido%}

templates/empleados/empleados.html
{%extends 'base.html'%}
{%load static%}
{%block configuraciones%}
<link href = "{%static 'css/empleados/tabla.css'%}" rel = "stylesheet"/>
{%endblock configuraciones%}
{%block administrar%}
<div>
    <a href = "{%url 'empleado_app:administrar'%}" style = "color:red">Administrar</a>
</div>
<div>
    <a href = "{%url 'empleado_app:registrar'%}" style = "color:red">Registrar</a>
</div>
{%endblock administrar%}
{%block contenido%}
<br/>
<div class = "busqueda">
    <form method = "GET">
        <input type = "text" class = "caja_busqueda" placeholder = "Nombre empleado" id = "nombre" name = "nombre">
        <input type = "submit"/ value = "🔍︎" class = "boton_buscar">
    </form>
</div>
<div class = "contenedor_global">
    <div>
        <table>
            <tr>
                <th>
                    NOMBRES
                </th>
                <th>
                    APELLIDOS
                </th>
                <th>
                    DEPARTAMENTO
                </th>
                <th>
                    ACCION
                </th>
            </tr>
            {% for i in empleado %}
            <tr>
                <td>
                    {{i.nombre_empleado}}
                </td>
                <td>
                    {{i.apellido_empleado}}
                </td>
                <td>
                    {{i.departamento.nombre_departamento}}
                </td>
                <td>
                    <a href = "{%url 'empleado_app:Detallado' i.id%}">VER</a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
    <div class = "pagina">
        {%if is_paginated%}
        <ul>
            {% if page_obj.has_previous%}
            <li>
                <a href = "?page={{page_obj.previous_page_number}}"><<</a>
            </li>
            {%endif%}
            {% for pagina in paginator.page_range%}
            {% if pagina == page_obj.number %}
            <li>
                <a href = "?page={{pagina}}" class = "pagina_actual">{{pagina}}</a>
            </li>
            {%else%}
            <li>
                <a href = "?page={{pagina}}">{{pagina}}</a>
            </li>
            {% endif%}
            {%endfor%}
            {% if page_obj.has_next%}
            <li>
                <a href = "?page={{page_obj.next_page_number}}">>></a>
            </li>
            {%endif%}
        </ul>
        {%endif%}
    </div>
    {%endblock contenido%}
</div>

templates/home/inicio.html
{%extends 'base.html'%}
{%load static%}
{%block configuraciones%}
<link href = "{%static 'css/home/nosotros.css'%}" rel = "stylesheet"/>
{%endblock configuraciones%}
{%block titulo%}Inicio{%endblock titulo%}
{% block contenido %}
<div class = "contenedor_grande">
    <div>
        <div class = "caja_texto_2">
            <h1>nosotros</h1>
        </div>
        <div class = "caja_texto">
            <p>Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creación de las hojas "Letraset", las cuales contenian pasajes de Lorem Ipsum, y más recientemente con software de autoedición, como por ejemplo Aldus PageMaker, el cual incluye versiones de Lorem Ipsum.</p>
        </div>
    </div>
    <div>
        <div class = "caja_texto_2">
            <h1>EMPRESA</h1>
        </div>
        <div class = "caja_texto">
            <p>Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creación de las hojas "Letraset", las cuales contenian pasajes de Lorem Ipsum, y más recientemente con software de autoedición, como por ejemplo Aldus PageMaker, el cual incluye versiones de Lorem Ipsum.</p>
        </div>
    </div>
    <div>
        <div class = "caja_texto_2">
            <h1>GENERAL</h1>
        </div>
        <div class = "caja_texto">
            <p>Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creación de las hojas "Letraset", las cuales contenian pasajes de Lorem Ipsum, y más recientemente con software de autoedición, como por ejemplo Aldus PageMaker, el cual incluye versiones de Lorem Ipsum.</p>
        </div>
    </div>
</div>
<div class = "titulo_final">
    <h1>LOREM IPSUM LOREM IPSUM LOREM IPSUM</h1>
</div>
{% endblock contenido %}